{{- if .Values.ingress.enabled -}}
{{- $fullName := include "search.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
{{- end}}
---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "search.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $svcPort }}
{{- end}}